### ISSUE TITLE
Few questions...

### ISSUE THREAD

**Issue by dackom** [terikon/cordova-plugin-photo-library#1]
1. Is there way to use this plugin together with wkwebview? As it seems that cdvphotolibrary: cannot be accesed from wkwebview, at least not in ios10. Yes, I added it in CPS meta tag, as you suggesting, but it seems that wkvebview is ignoring it.
2. Is there plan to convert it to latest swift 3.0 code, because in latest Xcode 8, you can not build project anymore, unless you change a bunch of things.

**Comment by viskin** [comment]
Hi, thanks for being the first user of this library :)

1. I'm planning to use wkwebview in near future, but yes, currently it's support for everything that relates to web requests is too buggy for me. Not only access to cdvphotolibrary. So I personally subscribed to cordova-plugin-wkwebview-engine bug reports and just waiting for it to stabilize.
BTW got no problem with using the library with crosswalk on android.

2. I think I will convert to swift 3.0 in 2-3 month. I don't like the idea of upgrading my mac few weeks before planned release of our app. I know apple changed swift syntax alot, but I hope they have some automatic converter. Aren't they?

**Comment by dackom** [comment]
Noo, thank you for making this nice library. :)

1. Good to know that is working on crosswalk, but unfortunately from my experience, crosswalk was not that good idea. I choosed to use crosswalk mainly because of older devices, but it turns out that it makes things even worse in terms of speed and memory usage. HTML renders better ofcourse, but its usually slower on older devices. And not to mention clients questions like, why is our app 40mb now... :) but maybe I did something wrong... 

2. There is automatic converter, and I used i to convert this plugin. But even after that it showed some errors. With my zero knowledge of swift, I managed to fix some lines, but some other I just commented, because I didn't have idea what to do... :) Anyway, it is working now... Probably some feature is not working properly because of commenting those stuff, but for my needs I think its enough.

**Comment by viskin** [comment]
1. For me, crosswalk does a good thing of providing consistency. It's actual not only for older devices, but just different modern phones. Plus you can use modern features of the browser, this what we use a lot. Standard webview works differently on each phone and each version of android. But yes, app size grows like crazy. I know there's option to build minimal needed version of crosswalk which will be smaller, but I didn't try it yet.

2. OK. Sooner or later I will convert to swift 3, just not right now. I have a work to do with permission management in this library, which is more important.

Do you know if apps compiled with swift 3 are runnable on ios 9?

**Comment by dackom** [comment]
Well, after including your plugin and converting it into swift3, I still have this in build settings:
<img width="443" alt="screen shot 2016-10-16 at 15 53 30" src="https://cloud.githubusercontent.com/assets/11218933/19417904/c32b5244-93b8-11e6-9717-bd59cdb25982.png">

So I presume that it should work on older iOS, but I did not tested it on real device.

**Comment by viskin** [comment]
OK, thank you. I will try to convert to swift 3 as soon as I have time.

**Comment by viskin** [comment]
Swift 3 is now supported, thanks to @fiahfy. See #3 .

**Comment by dackom** [comment]
Great! Thank you. 😊
