### ISSUE TITLE
[Android] thumbnailURL ignoring "quality" option

### ISSUE THREAD

**Issue by endoplasmic** [terikon/cordova-plugin-photo-library#10]
The returned photo object's thumbnailURL is showing the default quality in the URL instead of the one passed into options:

_cdvphotolibrary://thumbnail?photoId=98%3B%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2F20161109_164248.jpg&width=924&height=520&**quality=0.5**_

Here is a snip of code that creates the error:

```js
  const photoLibrary = window.cordova.plugins.photoLibrary;
  photoLibrary.getLibrary(
    items => {
      // do stuff
    },
    error => {
      console.log('Error loading library:', error);
    },
    {
      thumbnailWidth: 924,
      thumbnailHeight: 520,
      quality: 0.8,
    }
  );

**Comment by viskin** [comment]
Please tell if v1.1.6 resolved this.

**Comment by viskin** [comment]
Closing it. Feel free to reopen if the problem persists.
