### ISSUE TITLE
This application is not allowed to access Photo data

### ISSUE THREAD

**Issue by Nuajan** [terikon/cordova-plugin-photo-library#11]
Hi and congrat for the plugin.
On Android, I'm getting message "Permission Denial: This application is not allowed to access Photo data"
when i try to save a video to the library.
It's an mp4 file previously downloaded using filetransfer plugin to directory cordova.file.externalDataDirectory (given by the file plugin)
The file is downloaded and in fact it is on the supposed directory...
then i execute

                    cordova.plugins.photoLibrary.saveVideo(store + fileName, 'MyAppName', 
                        function () { console.log('Yeah?');}, 
                        function (err) { console.log('No!'); console.log(err);});

 And that is when i get error.

In the manifest file i can see...
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

Any ideas on what's going on?

Many thanks.

**Comment by Nuajan** [comment]
Sorry but obviously forgot about asking for permissions. 
I'll give a try to confirm it was totally my wrong.
Regards

**Comment by viskin** [comment]
Ok, that's the idea. You get 'Permission Denial' error on plugin API call, explain to user why you need permission to proceed, and you then call requestAuthorization so user will authorize access to his photos.

**Comment by Nuajan** [comment]
Works perfectly as expected, man!
Closing issue - not an issue, relabe it if you want or delete, but maybe is useful for someone else in the future.

Regards.

**Comment by viskin** [comment]
Great. It definitely can be useful, thanks.
