### ISSUE TITLE
Cannot find module '../cordova/platform_metadata'

### ISSUE THREAD

**Issue by ptkdev** [terikon/cordova-plugin-photo-library#124]
```
cordova plugin add cordova-plugin-photo-library --variable PHOTO_LIBRARY_USAGE_DESCRIPTION="To choose photos" --save
Installing "cordova-plugin-photo-library" for ios
Installing "cordova-plugin-file" for ios
Installing "cordova-plugin-compat" for ios
Installing "cordova-plugin-add-swift-support" for ios
Adding cordova-plugin-photo-library to package.json
Saved plugin info for "cordova-plugin-photo-library" to config.xml
(node:61839) UnhandledPromiseRejectionWarning: Error: Cannot find module '../cordova/platform_metadata'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:77:12)
    at module.exports (/Users/ptkdev/cordova/meingifs/plugins/cordova-plugin-add-swift-support/src/add-swift-support.js:23:34)
```

**Comment by bwdrop** [comment]
@ptkdev This was a bug in cordova-plugin-add-swift-support, just update it to latest version (1.7.1)
```
cordova plugin rm cordova-plugin-add-swift-support
cordova plugin add cordova-plugin-add-swift-support
```

**Comment by ptkdev** [comment]
Thanks!

**Comment by zeeshananjumjunaidi** [comment]
I had this problem with swift plugin version now I upgrade it to 1.7.2.
install swift plugin before cordova-plugin-photo-library because this plugin is using 1.6.0
@bwdrop Thanks!

**Comment by omeasraf** [comment]
If you already installed cordova-plugin-photo-library then you can just force remove cordova-plugin-add-swift-support and then add it back. This should fix the problem.
`cordova plugin rm cordova-plugin-add-swift-support --force
   cordova plugin add cordova-plugin-add-swift-support
`
and for ionic
`ionic cordova plugin rm cordova-plugin-add-swift-support --force
  ionic  cordova plugin add cordova-plugin-add-swift-support
`

**Comment by v-ken** [comment]
I love you man

**Comment by fdambrosio** [comment]
thanks @omeasraf

**Comment by KiwiKilian** [comment]
To make this fix more permanent you will have to add `cordova-plugin-add-swift-support` before `cordova-plugin-photo-library` in your `config.xml` just like so:
```xml
...
    <plugin name="cordova-plugin-add-swift-support" spec="1.7.2" />
    <plugin name="cordova-plugin-photo-library" spec="2.2.1">
        <variable name="PHOTO_LIBRARY_USAGE_DESCRIPTION" value="" />
    </plugin>
...
```

I'm not into the plugin development, but couldn't  this be fixed by simply bumping the dependency version in the [plugin.xml](https://github.com/terikon/cordova-plugin-photo-library/blob/master/plugin.xml#L40)?

**Comment by NishithaSurapudi** [comment]
I have got the same error after adding geo fence plugin
swift plugin got installed while geofencing is installing...can someone help me!Thanks in advance
