### ISSUE TITLE
Not able to show taken image when saving as Native URI

### ISSUE THREAD

**Issue by vitorsilvalima** [terikon/cordova-plugin-photo-library#126]
Hi guys, I have a question,  I have tried to show the taken picture by the library using the img tag as shown bellow
takenpic = file:///storage/emulated/0/Android/data/io.ionic.starter/cache/1523591095707.jpg
<img [scr]='takenpic' />

However, it does not work at all. Can someone please let me know why. I may be doing something wrong

**Comment by stephenmutua254** [comment]
@vitorsilvalima did you find solution to this?
