### ISSUE TITLE
android: getLibrary should return its results in chunks

### ISSUE THREAD

**Issue by viskin** [terikon/cordova-plugin-photo-library#14]

**Comment by viskin** [comment]
See #13

**Comment by dnmd** [comment]
I came across this plugin and noticed a "cancel" function, to cancel the "fetching" process. It might be of inspiration: [cordova-plugin-photos](https://github.com/domax/cordova-plugin-photos) :)

**Comment by viskin** [comment]
Yeah, cancelling may be useful. I will add this to TODO list.

**Comment by viskin** [comment]
For iOS, implemented in v1.2.0.
Android implementation needed.

**Comment by kartagis** [comment]
#34 related?

**Comment by viskin** [comment]
@kartagis It can be related. When there's very large amount of photos, just returning their names and paths takes some time.
This problem can be addressed in few ways:
- Chunks functionality will quickly return some data to display in small parts. Currently it implemented on iOS, and I want to change the way it implemented a little.
- Returning images by folder (library) can also reduce waiting time (this will be implemented in near future).

**Comment by viskin** [comment]
Implemented in v2.0

**Comment by kosssi** [comment]
Hello @viskin in v2.0 or in v1.2.2?

**Comment by viskin** [comment]
v2.0, it is in active development and that's what appears in master branch.
I will publish it as 2.0 after filtering by album will be implemented (it's
50% now).
