### ISSUE TITLE
Issue with Add Swift Support

### ISSUE THREAD

**Issue by alickbuscariolli** [terikon/cordova-plugin-photo-library#166]
Hi,
Since I am using Finger Print in my project which requires cordova-plugin-add-swift-support version 2.0.2 I am not being able to install Photo Library which requires cordova-plugin-add-swift-support version ˆ1.6.0

I am facing the following error:
Failed to install 'cordova-plugin-photo-library': CordovaError: Version of installed plugin: "cordova-plugin-add-swift-support@2.0.2" does not satisfy dependency plugin requirement "cordova-plugin-add-swift-support@^1.6.0". Try --force to use installed plugin as dependency.

Does anyone know a solution for that?
Thank you

**Comment by ciroanni** [comment]
Hi @alickbuscariolli, how do you solve the issue? Thanks in advance

**Comment by Shtibel** [comment]
Same problem
How do you solve this ?

**Comment by sytzez** [comment]
I'd like to know the solution as well

**Comment by sytzez** [comment]
Solved it by using this fork:
https://github.com/nilebma/cordova-plugin-photo-library

**Comment by JianhuisHuang** [comment]
> Solved it by using this fork:
> https://github.com/nilebma/cordova-plugin-photo-library

This fork work for me, thanks
