### ISSUE TITLE
Filter by album

### ISSUE THREAD

**Issue by viskin** [terikon/cordova-plugin-photo-library#17]
Currently getLibrary returns all photos on device.
It would be nice to add an option to select only specific albums.

**Comment by kosssi** [comment]
thanks for your plugin is really awesome!

Very good job 😍

**Comment by viskin** [comment]
@kosssi Thank you

**Comment by viskin** [comment]
This functionality is not needed. One can ask for all the items from getLibrary, including album data, and then filter by album. Each libraryItem has attached albumIds array.

**Comment by flogr** [comment]
Hi @viskin 
filtering by an album name can be done the way you explain it, but its slow when a user has a lot of albums, i experienced it with a customers device.
I think the possibility to select a specific album in getLibrary which then only fetches and returns the items from this album would greatly increase performance for issues like this.

I'm thinking bout something like:
photoLibrary.getLibrary({albumId: "123456"})

What do you think about that?
