### ISSUE TITLE
iOS: Provide very low-quality image by getThumbnail()

### ISSUE THREAD

**Issue by fiahfy** [terikon/cordova-plugin-photo-library#19]
Call `getThumbnail()`, and get thumbnail blob.
But the provided blob is very low-quality image by ignoring thumbnailWidth, thumbnailHeight and quality.

`PHCachingImageManager`
`requestImage(for:targetSize:contentMode:options:resultHandler:)`
This method is explained as following 
> By default, this method executes asynchronously. If you call it from a background thread you may change the isSynchronous property of the options parameter to true to block the calling thread until either the requested image is ready or an error occurs, at which time Photos calls your result handler.
> For an asynchronous request, Photos may call your result handler block more than once. Photos first calls the block to provide a low-quality image suitable for displaying temporarily while it prepares a high-quality image. (If low-quality image data is immediately available, the first call may occur before the method returns.) When the high-quality image is ready, Photos calls your result handler again to provide it. If the image manager has already cached the requested image at full quality, Photos calls your result handler only once. The PHImageResultIsDegradedKey key in the result handler’s info parameter indicates when Photos is providing a temporary low-quality image.
> 

I think that deliveryMode is changed to `.highQualityFormat` because result handler is called once.
```
        thumbnailRequestOptions.deliveryMode = .highQualityFormat
```
What do you think?

Sorry my English.

**Comment by viskin** [comment]
I guess the simplest way to handle this will be to stick to highQualityFormat for thumbnail.

**Comment by fiahfy** [comment]
I think so too.
I created PR, and this works well on my project.
