### ISSUE TITLE
writing a blob or HTMLImageElement

### ISSUE THREAD

**Issue by pliablepixels** [terikon/cordova-plugin-photo-library#20]
Hi there, I have a blob or an HTMLImageElement (both versions are possible) that I need to write to my gallery. It is mandatory to convert to base64 or is there a way to directly write the object to the gallery ? converting to base64 takes up a lot of memory (its a 22MB animated GIF blob)

thanks

**Comment by viskin** [comment]
What you can do is save your blob to a temporary file (see [FileSystem API](https://www.html5rocks.com/en/tutorials/file/filesystem/)).
Then you call photoLibrary.saveImage or photoLibrary.saveVideo with file URL you've get. It will save to library without Base64 overhead.

**Comment by pliablepixels** [comment]
thanks!
