### ISSUE TITLE
Build fails in PhoneGap build

### ISSUE THREAD

**Issue by blukis** [terikon/cordova-plugin-photo-library#23]
iOS build fails on build.phonegap.com, log output attached.
[build.zip](https://github.com/terikon/cordova-plugin-photo-library/files/629789/build.zip)

**Comment by viskin** [comment]
Yeah, it seems PhoneGap build still does not support Swift, see [this issue](https://github.com/phonegap/build/issues/521).
As cordova-plugin-photo-library implemented in Swift, the only way around it is to wait PhoneGap to support Swift, sorry.
