### ISSUE TITLE
Add function witch return all album name

### ISSUE THREAD

**Issue by kosssi** [terikon/cordova-plugin-photo-library#24]
It's cool if I can add this feature.
Maybe copy https://github.com/SuryaL/cordova-gallery-api getAlbums

**Comment by viskin** [comment]
It would be great, let's discuss the API.
I think there should be a function that returns all albums on the device. Say **getAlbums()**.
Each album returned will be an object with **{id, name}**.
Then, as in #17, getLibrary should get **additional option**. Say, 

      options = { albums: [album1, album2] }.
      Or alternatively options = { albums: [albumId1, albumId2] }.

So getLibrary will return only wanted albums. If albums option not provided, getLibrary will return everything, just as it does now.
In addition, it would be nice to add to each libraryItem that getLibrary returns, additional property, say **albumId** - album id where the item resides.

What do you think?

**Comment by kosssi** [comment]
I'm agree with all your comment. 👍

I start it monday ;)

**Comment by viskin** [comment]
Great.
Are you planning to implement Android, iOS, or maybe both?

**Comment by kosssi** [comment]
In first time Android, I never write code with swift ;)

**Comment by viskin** [comment]
Ok. I can add iOS implementation afterwards.

**Comment by viskin** [comment]
Working on this.

**Comment by viskin** [comment]
Done for v2.0
