### ISSUE TITLE
Add option for date format

### ISSUE THREAD

**Issue by kosssi** [terikon/cordova-plugin-photo-library#26]
It's an idea for new feature

**Comment by viskin** [comment]
Why would it be useful?
One can always change the date format in client app.

**Comment by kosssi** [comment]
Because Android iOS are not the same format:
- iOS : "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
- Android : "yyyy-MM-dd HH:mm a z"

I can change it if you want?

**Comment by viskin** [comment]
Ok, I libraryItem that getLibrary() returns contains **creationDate** property.
If I understand right, now it is string.
I think it should be JavaScript **Date** object. If it will be Date object, it has no format. So our problem is that creationDate is still string?

**Comment by viskin** [comment]
From now on, creationDate is provided as Date object.
