### ISSUE TITLE
getPhoto and getThumbnail return empty Blob

### ISSUE THREAD

**Issue by kosssi** [terikon/cordova-plugin-photo-library#27]
On my android 7.1.1

I would like make more test on others devices.

**Comment by viskin** [comment]
Please do it, never experienced such issue.

**Comment by kosssi** [comment]
it's ok on your Android device ?

**Comment by viskin** [comment]
Yeah, but I tested it on android 6 and android 4.1
Can you attach a code that causes the problem?

**Comment by kosssi** [comment]
I search a picture:

```
cordova.plugins.photoLibrary.getLibrary(
  function (library) { console.log(library[0]); picture = library[0]; },
  function (err) { console.log(err); },
  {}, // optional options
  function partialCallback(partialLibrary) {} // optional
);
```

After get picture:

```
cordova.plugins.photoLibrary.getPhoto(
  picture,
  function (fullPhotoBlob) { console.log(fullPhotoBlob); },
  function (err) { console.log(err); }
);
```

Result:

```
Blob {size: 0, type: ""}
```

This code is good on iOS but not on Android.

**Comment by viskin** [comment]
I will try it tomorrow on my device.

**Comment by kosssi** [comment]
I test it on Android 7.1.1, Android 6, and emulator (Android 5, Android 7) it's same result.

On monitor:
```
12-15 09:38:30.610: I/ExifInterface_JNI(4047): Raw image not detected
12-15 09:38:30.653: D/SystemWebChromeClient(4047): : Line 4 : [object Blob]
12-15 09:38:30.653: I/chromium(4047): [INFO:CONSOLE(4)] "[object Blob]", source:  (4)
```

**Comment by viskin** [comment]
Yep, indeed there's problem. Looking into it...

**Comment by viskin** [comment]
Oh, it seems they changed something in [cordova-android](https://github.com/apache/cordova-android) that made it stop working. I just tried to run the same code with following:

      <engine name="android" spec="~5.0.0" />

and it works:

      Blobsize: 13068 type: "image/jpeg" __proto__: Blob

**Comment by viskin** [comment]
I tend to think the difference that causes problem is here:
5.x.x: runs as nativeToJsModes.ONLINE_EVENT
[see it here](https://github.com/apache/cordova-android/blob/5.0.x/bin/templates/project/assets/www/cordova.js#L903)

6.x.x: runs as nativeToJsModes.EVAL_BRIDGE
[see it here](https://github.com/apache/cordova-android/blob/6.1.x/bin/templates/project/assets/www/cordova.js#L928)

I don't know what EVAL_BRIDGE is and why it ignores multipart plugin result we send from getPhoto and getThumbnail functions. But I have strong feeling that this difference between 6.x and 5.x causes the problem.

**Comment by kosssi** [comment]
Ok, I hope it's possible to resolve it.

**Comment by viskin** [comment]
Yeah, the issue seems not very complex - how to return 2 values (image data and mime type) from plugin? Currently what it does is uses multipart return type. It seems that cordova broke this functionality in android-cordova 6.x (possibly by using EVAL_BRIDGE which I don't know what).
I pretty sure there is simple solution to return 2 values, but it should work on iOS too.

**Comment by viskin** [comment]
Indeed it was a problem with new cordova-android 6.x. It broke support for multipart plugin results.
Resolved this with manually preparing plugin result as JSON.
