### ISSUE TITLE
Retrieve all EXIF info

### ISSUE THREAD

**Issue by dackom** [terikon/cordova-plugin-photo-library#32]
I tried with cordova.plugins.photoLibrary.getPhoto function, as well as reading photoURL with XHR request, and neither way does return file with EXIF info. Only EXIF info that I see is:

Orientation - Right top
ExifOffset - 38
ColorSpace - sRGB
ExifImageWidth - 2576
ExifImageHeight - 1932

Is there way to retrieve all EXIF info from photo, like location, date/time taken, camera type... etc... all?

**Comment by viskin** [comment]
What platform is it? I assume Android, as iOS does not permit to retrieve EXIF info at all AFAIK.

The library struggles to return correctly oriented image. EXIF information is lost during this process. It might be possible to re-apply EXIF information to the image, but I have no plans in doing so.

You can use libraryItem.nativeURL property, as on Android it returns unprocessed url of the image, that will retain all the EXIF data.

**Comment by dackom** [comment]
Ok... thank you. I was trying to get it on iOS... its good to know that is not possible. 😞

**Comment by viskin** [comment]
Maybe I should correct myself.
Extracting EXIF information on iOS with **API that this library currently uses** seems not possible.
There is definitely possibility to do it, for example [this app](https://itunes.apple.com/il/app/viewexif/id945320815) extracts EXIF info.
Just not with this library. Any suggestions appreciated.

**Comment by dackom** [comment]
Hm.. I'm a bit confused now... is it that original JPEG files that are stored in camera roll in iOS, they don't have EXIF data embedded? So EXIF is stored elsewhere?

I'm not really getting, how this plugin actually works? You are using some Apple's API to get images from Camera Roll? And with that API calls, you don't get anything other except raw image data? So you don't get real files or EXIF? 

Google Photos is also getting all data. Its even getting live pictures video on iPhone 6s.

Sorry about dumb questions, i'm just a front-end developer, I don't know much about swift or how is it all working...

**Comment by viskin** [comment]
> I'm not really getting, how this plugin actually works? You are using some Apple's API to get images from Camera Roll? And with that API calls, you don't get anything other except raw image data? So you don't get real files or EXIF?

Exactly.
I'm pretty noob in iOS development, so I can't tell exactly how iOS stores EXIF data. I'm just sure that extracting this data is possible.

**Comment by viskin** [comment]
To make things little better, latitude and longitude were added to libraryItem in latest version.

**Comment by dackom** [comment]
Great work. :)
Do you have some technique to embed it in JPG file exif, before upload... or you are doing that on server side?

**Comment by viskin** [comment]
I think it's technically possible to embed EXIF data into photos. After all, the plugin builds image data as row bytes, part of this process could be embedding EXIF.
But I don't have time/need to implement this. Additionally, this can slow things down. For now, I prefer to keep things like location to be in libraryItem structure and not in image itself.

**Comment by matthieu80** [comment]
@dackom 
hi there,
Have you found a solution for this?
I am stuck... :-/
thank you

**Comment by dackom** [comment]
Unfortunately no. 😕
