### ISSUE TITLE
Error: Undefined is not a function

### ISSUE THREAD

**Issue by metalaureate** [terikon/cordova-plugin-photo-library#4]
`cordova plugin add cordova-plugin-photo-library --variable PHOTO_LIBRARY_USAGE_DESCRIPTION="To choose photos" --save`

returns

`Error: undefined is not a function`

This error also occurs when I try to build the app.

Occurs when building iOS or Android. I removed/added platforms.

Cordova CLI: 6.1.1
Gulp version:  CLI version 3.9.1
Gulp local:  
Ionic Framework Version: 1.3.1
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: Mac OS X El Capitan
Node Version: v0.12.2
Xcode version: Xcode 8.0 Build version 8A218a 

Any ideas? I would love to use this plugin.

**Comment by metalaureate** [comment]
Appears to originate from the `cordova-plugin-add-swift-support` plugin. I'll close this ticket,

**Comment by viskin** [comment]
I tried adding both plugins to new clean cordova project, and both worked fine:

      cordova plugin add cordova-plugin-add-swift-support --save
      cordova plugin add cordova-plugin-photo-library --variable PHOTO_LIBRARY_USAGE_DESCRIPTION="To choose photos" --save

I use slightly different version of cordova, and your node version looks very outdated.
I have:

- cordova 6.3.1
- node 6.4.0

I suggest trying this on clean project (cordova create), and with node 6.x.x.

**Comment by metalaureate** [comment]
My node version was too old. Thanks!
