### ISSUE TITLE
Maintain Aspect ratio of resized thumbnails

### ISSUE THREAD

**Issue by JohnCMcDonough** [terikon/cordova-plugin-photo-library#43]
I make a call to getLibrary similar to this:

`var width = 256;`
`PhotoLibrary.getLibrary({thumbnailWidth: width})`

Photos don't maintain aspect ratio when being resized. Is there a temporary workaround, or better solution to do what I'm trying to do? I know that I can pass in a thumbnailHeight, but that stretches the image.

Edit: Nevermind, this issue appeared related to my CSS, not this library itself.

**Comment by viskin** [comment]
You welcome
