### ISSUE TITLE
gif saved as static image

### ISSUE THREAD

**Issue by gusreyes01** [terikon/cordova-plugin-photo-library#49]
Hi, first thanks for an awsome library. Works great.

I'm trying to save an gif on the gallery but it's saved as an static image.

Is there any workaround ?

Here's the url of the image I'm trying to save as gif: http://i.imgur.com/WI1A58C.gif

**Comment by viskin** [comment]
I will try this...

**Comment by gusreyes01** [comment]
@viskin I think it just looks static in the gallery, I can share it through WhatsApp as a gif with no problems. Sorry to bother you.

**Comment by viskin** [comment]
NP 👍
