### ISSUE TITLE
(IOS) can not upload photo.

### ISSUE THREAD

**Issue by mayajuni** [terikon/cordova-plugin-photo-library#51]
i tested to upload photo on ios and android.  android is very good. but ios can not upload.

error is..
FileTransferError
  body: null
  code: 1
  exception: null
  http_status: null
  source: "cdvphotolibrary://photo?photoId=67E3D042-F2D7-4FC2-A205-
  AE5E27A95336%2FL0%2F001"

how can i upload photo on ios? 
sorry for not good English.

**Comment by viskin** [comment]
Can you please provide your code?

**Comment by viskin** [comment]
Will this code work for you?
```js
cordova.plugins.photoLibrary.getPhoto(libraryItem, function(blob){
  var dataURI;
  var reader = new FileReader();
  reader.onload = function(){
    dataURI = this.result;
    // upload the dataURI with cordova-plugin-file-transfer
  };
  reader.readAsDataURL(blob);
});
```

**Comment by mayajuni** [comment]
@viskin 
Thenk you so much. 
I solved this problem with your help.

**Comment by viskin** [comment]
Glad to hear.
Closing the issue.
