### ISSUE TITLE
Failing to save image from a URL

### ISSUE THREAD

**Issue by mkj-git** [terikon/cordova-plugin-photo-library#55]
I am getting error like

/storage/emulated/0/Android/data/com.ionicframework.maapp301549890139879898799/files/mobapp/images/IMG-1493259358390.jpg: open failed: ENOENT (No such file or directory)

**Comment by viskin** [comment]
What is your code that causes this error?

**Comment by mkj-git** [comment]
```
    	var targetPath = cordova.file.externalDataDirectory + Constants.APP_DIR_IMAGES + "/IMG-" + new Date().getTime() + ".jpg";
    	cordova.plugins.photoLibrary.saveImage(targetPath, "maApp", function (libraryItem) {
    		console.log(libraryItem);
    	}, function (err) {
    		console.log(err);
    	});
```

**Comment by viskin** [comment]
Ah, got it.
saveImage is actually `saveImage(sourcePath, targetAlbum, ...)`. So you should take care to put your photo to the storage (preferably temporary storage), and then call saveImage to save it to device's gallery.

**Comment by mkj-git** [comment]
You mean first i should save to temp folder then i should pass that path as source ? can you show some example?

**Comment by viskin** [comment]
If you use [cordova-plugin-file-transfer](https://github.com/apache/cordova-plugin-file-transfer), you can use resolveLocalFileSystemURL() like this:
```js
var fileTransfer = new FileTransfer();
var uri = encodeURI("http://some.server.com/download.php");
fileTransfer.download(uri, 'cdvfile://localhost/temporary/path/to/image.jpg', function (entry) {
   var targetPath= entry.toURL();
   cordova.plugins.photoLibrary.saveImage(targetPath, "myApp", function (libraryItem) {
...
```

**Comment by mkj-git** [comment]
This is working now

**Comment by viskin** [comment]
Great, closing

**Comment by arulyan** [comment]
### Another way of writing the code can be:
```
var album = 'IonicWallpapers';
    this.file.readAsDataURL(this.file.applicationDirectory+"www/assets/imgs/", picture.jpg) //this.file.applicationDirectory gives the loacation of the image with respect to the localhost
    .then((dataURL:string) => {
      cordova.plugins.photoLibrary.saveImage(dataURL, album, function (libraryItem) {alert("good");}, function (err) {alert("url "+image+" not working");});
    })
```
