### ISSUE TITLE
How to get Coverphoto of an Album?

### ISSUE THREAD

**Issue by Dineshrajaa** [terikon/cordova-plugin-photo-library#75]
Hi everyone,

 I would like to know is there any possible way to get the Thumbnail/Cover Photo of an Album currently 
`getAlbums` is returning id and name of the album, will be great if an URL of Cover Photo is also returned.

Please let me know your thoughts.

**Comment by AndreasGassmann** [comment]
I have briefly looked into this as well, but I think the only way is to load the pictures of each album and then taking the first one as cover photo. The pictures are sorted newest to oldest so this should work fine.

**Comment by Dineshrajaa** [comment]
Okay then I would like to close this  for now :) waiting for that feature though
