### ISSUE TITLE
How to get latest photos first?

### ISSUE THREAD

**Issue by kanezeng** [terikon/cordova-plugin-photo-library#78]
Currently, I can get the plugin up and running, but it always return the oldest photo first.
Is there any way to get the latest photo first?

**Comment by AndreasGassmann** [comment]
I changed the behaviour in this PR https://github.com/terikon/cordova-plugin-photo-library/pull/70. Are you using the latest version?

**Comment by kanezeng** [comment]
According to : https://github.com/apache/cordova-plugin-camera/releases
The latest version is 2.4.1 which was released at Apr 28.
PR #70 was merged at Aug 18. Can I install the release contains this PR? @AndreasGassmann

**Comment by kanezeng** [comment]
Thanks @AndreasGassmann , I upgraded to the latest version, and it works now.
