### ISSUE TITLE
Album created not showing in gallery of device.

### ISSUE THREAD

**Issue by LtotheWT** [terikon/cordova-plugin-photo-library#82]
Hi guys i am using ionic 3, i have successfully created an album and save image to it. However the album is not shown in my device. Any idea i can make the album visible in my gallery ?
device- android, xiaomi red mi note 3

**Comment by Story5** [comment]
Have the same issue，How to solve？

**Comment by LtotheWT** [comment]
The album is created, i found it at more albums in my gallery
