### ISSUE TITLE
[Android] Orientation of images is incorrect when using 16:9 aspect ratio in options

### ISSUE THREAD

**Issue by endoplasmic** [terikon/cordova-plugin-photo-library#9]
The thumbnails that are returned are being rotated 90 degrees counter-clockwise, but cropped correctly.

Here is a snip of code that is producing the error:

```js
  const photoLibrary = window.cordova.plugins.photoLibrary;
  photoLibrary.getLibrary(
    items => {
      // do stuff
    },
    error => {
      console.log('Error loading library:', error);
    },
    {
      thumbnailWidth: 924,
      thumbnailHeight: 520,
      quality: 0.8,
    }
  );

**Comment by viskin** [comment]
Checking this...

**Comment by viskin** [comment]
I saw 226026d41a7eb169edafeaefaeaf0892c002bb62 in your PR #12.
You added orientation value to library item.
I wonder how orientation value can be used in JavaScript? I'd prefer that photos just appear in correct orientation as I ask for them, and if it will work, is there any value in orientation field for the app?

**Comment by viskin** [comment]
I tried values you provided on different photos taken in different orientation on my device (nexus 5x), thumbnails appear right.
Can you please send a photo that appears rotated to my email, so I will try to debug it.

**Comment by endoplasmic** [comment]
Sent to your e-mail and also attaching here. Tested on Note 5, S6 Edge+, S7 Edge.

![20161111_095127](https://cloud.githubusercontent.com/assets/118301/20224785/0f9a7ef2-a7f5-11e6-8b88-0d97b4ff3995.jpg)

**Comment by viskin** [comment]
Yeah, the photo definitely has interesting property inside that causes rotation.
I'll check it tomorrow.

**Comment by viskin** [comment]
Wow, orientation issue is total mess. Here's article I found about the issue:
http://www.daveperrett.com/articles/2012/07/28/exif-orientation-handling-is-a-ghetto/
And this repo contains test images of all possible orientations:
https://github.com/recurser/exif-orientation-examples

**Comment by viskin** [comment]
browser platform of photo-library displays images incorrectly because browsers display them incorrectly. I use it only for development, so I don't feel correcting the issue for browser makes sense. Most of sites, including github, have this issue.
iOS looks free of this issue, so only platform to fix is android.

**Comment by viskin** [comment]
Oh man, rotation and EXIF is so hardly broken on android that fixing this bug ended up in project of itself.
For example, MediaStore.Images.ImageColumns.ORIENTATION returns incorrect rotation for some images.
Happily, ExifInterface always works.
I published version 1.1.8, please try it on your file.
I checked it with all images of https://github.com/recurser/exif-orientation-examples, and it looks fine.

**Comment by endoplasmic** [comment]
I will give this a whirl later on. But thanks for looking into this. I'm replying on my iOS device and my attached photo looks fine. Go figure.

**Comment by viskin** [comment]
Closing it after checking on device.

**Comment by endoplasmic** [comment]
The rotation portion is working great now, but it's ignoring the image itself and putting black bars on the sides.

The image I posted is rotated correctly, but I can see the whole image instead of cropping and centering like you do with images that are not rotated.

**Comment by viskin** [comment]
I don't have this problem in my app.
1. On what version of plugin black bars happen? I tries 1.1.10. Please try latest if it's not.
2. Please give me a screenshot of wrong appearance of the image. Are we talking about thumbnail or whole image?

**Comment by viskin** [comment]
I use ThumbnailUtils.extractThumbnail method now and it seems to work.
Please confirm that this branch solves the black borders problem for you:
https://github.com/terikon/cordova-plugin-photo-library.git#fix-rotated-thumbnail

**Comment by endoplasmic** [comment]
Yup, that did the trick. Nice work!
